shopList:
    path: /
    controller: App\Controller\SushiShopController::shopCart
#shopList:
#  path: /list
#  controller: App\Controller\SushiShopController::index
shopItem:
  path: /item/{id<\d+>}
  controller: App\Controller\SushiShopController::shopItem
shopCart:
  path: /cart/
  controller: App\Controller\SushiShopController::shopList