index:
    path: /
    controller: App\Controller\SushiShopController::shopList
shopList:
  path: /list/
  controller: App\Controller\SushiShopController::index
shopItem:
  path: /item/
  controller: App\Controller\SushiShopController::shopItem